#!/usr/bin/env python3
from pathlib import Path
from n4d.client import Client

key_file = Path("/etc/n4d/key")

if not key_file.exists():
    return 

with key_file.open('r') as fd:
    key = key_file.readline().strip()

c = Client(key=key)
c.startup_on_demand("NATFREE_STARTUP",True)
